#!/bin/bash

###############################################################################
# Copyright (c) 2013      Los Alamos National Security, LLC.
#                         All rights reserved.
################################################################################

echo "starting autoreconf..."

if [[ ! -d m4 ]]; then
    mkdir m4
fi

autoreconf --force --install

exit $?
